name: bootes_app
description: Estação de monitoramento mobile do CubeSat Bootes.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.16.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^2.4.0
  flutter_native_splash: ^2.3.1


flutter_native_splash:
  color: "#E7E6D5"
  image: assets/images/bootes.png

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/bootes.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
